### PR TITLE
Moved ZSSimageDevice.png to correct path

### PR DESCRIPTION
**Pull request by william205**
Moved ZSSimageDevice.png from root folder to the source/images folder as discussed in issue #132

### CODE REVIEW

**Comment by nnhubbard** [comment]
@william205 Thanks! You interested in helping more with this project?

**Comment by william205** [comment]
Yeh sure, I would be happy to help more.

**Comment by nnhubbard** [comment]
I just need someone to head up the project as I really don't have time to take it on anymore.

**Comment by william205** [comment]
I would be happy to head up the project.

**Comment by nnhubbard** [comment]
@william205 I just added you as a collaborator on the project. Thank you!

**Comment by william205** [comment]
Great, thanks! No problem.

**Pull request merged**
